### PR TITLE
fix network_bootstrap

### LINKED ISSUE #444: API Fix: Remove redundant child in `network_bootsrap()`
Network bootsrap doesn't need to return `Option<Child>`.

### PR DESCRIPTION
**Pull request by mojoX911**
closes #444

### CODE REVIEW

File: src/maker/server.rs [hunk 1]
```diff
@@ -45,9 +44,9 @@ use crate::maker::error::MakerError;
 ///
 /// Tor thread is spawned only if ConnectionType=TOR and --feature=tor is enabled.
 /// Errors if ConncetionType=TOR but, the tor feature is not enabled.
-fn network_bootstrap(maker: Arc<Maker>) -> Result<(Option<Child>, String, String), MakerError> {
```
Comment (KnowWhoami) [inline src/maker/server.rs:48]: Can you please update the doc comments accordingly.

**Review by KnowWhoami — APPROVED** [review]
Ack..
Just doc commets changes are required -> then it's good to go..
